'use strict';
(()=>{
  const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  let project={name:'ネットワーク更改案件',revision:1,sources:[],requirements:[]},workflow=null,chunks=[],chunk=0,dirty=false,busy=false,url=null;
  function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':'';$('message').setAttribute('role',error?'alert':'status');}
  function revoke(){if(url){URL.revokeObjectURL(url);url=null;}$('download').hidden=true;}
  function changed(){project.revision++;workflow=null;dirty=true;revoke();renderFlow();$('saveStatus').textContent='変更あり・未保存';}
  function download(data,name,type='application/octet-stream'){const link=el('a');const u=URL.createObjectURL(new Blob([data],{type}));link.href=u;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(u),60000);}
  const action=(id,fn)=>$(id).addEventListener('click',()=>run(fn));
  async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button,input,textarea,select').forEach(b=>b.disabled=true);try{await fn();}catch(e){message(e.message||String(e),true);}finally{busy=false;document.querySelectorAll('button,input,textarea,select').forEach(b=>b.disabled=false);updateButtons();}}
  function updateButtons(){const complete=workflow&&NWCore.steps.every(k=>workflow.stages[k]);$('export').disabled=busy||!complete;$('extract').disabled=busy||!project.sources.length;$('start').disabled=busy||!project.requirements.length;$('prev').disabled=busy||chunk===0;$('next').disabled=busy||chunk>=chunks.length-1;['copy','promptFile','accept','responseFile'].forEach(id=>$(id).disabled=busy||!chunks.length);}
  function renderSources(){const list=$('sourceList');list.replaceChildren();for(const s of project.sources){const row=el('li'),label=el('span',s.name+' · '+s.body.length.toLocaleString()+'字'),button=el('button','削除','secondary');button.addEventListener('click',()=>run(()=>{project.sources=project.sources.filter(x=>x.id!==s.id);project.requirements=project.requirements.map(r=>r.source_id===s.id?{...r,source_id:'',source:'元資料削除：'+s.name,status:'unresolved'}:r);changed();renderSources();renderRequirements();message('資料を削除しました。関連要件は「未解決」として残しています。');}));row.append(label,button);list.append(row);}}
  function renderRequirements(){const list=$('requirements');list.replaceChildren();$('requirementCount').textContent=project.requirements.length+'件';for(const r of project.requirements){const box=el('div',undefined,'requirement'),head=el('div',undefined,'section-title'),label=el('strong',r.id),select=el('select');select.setAttribute('aria-label',r.id+'の状態');for(const [value,title] of [['candidate','候補'],['confirmed','確認済み'],['unresolved','未解決']]){const o=el('option',title);o.value=value;select.append(o);}select.value=r.status;select.addEventListener('change',()=>{r.status=select.value;changed();});const remove=el('button','削除','secondary');remove.addEventListener('click',()=>run(()=>{project.requirements=project.requirements.filter(x=>x!==r);changed();renderRequirements();}));head.append(label,select,remove);const body=el('textarea');body.rows=2;body.maxLength=3000;body.value=r.text;body.setAttribute('aria-label',r.id+'の本文');body.addEventListener('change',()=>{if(!body.value.trim()){body.value=r.text;message('要件本文を空にはできません。不要なら削除してください。',true);return;}r.text=body.value;changed();});box.append(head,body,el('p',r.source,'hint'));list.append(box);}}
  function showChunk(){$('prompt').value=chunks[chunk]||'';$('chunkStatus').textContent=chunks.length?`依頼文 ${chunk+1} / ${chunks.length}（番号順に同じCopilotチャットへ貼り付け）`:'';updateButtons();}
  function renderFlow(){chunks=[];chunk=0;$('workflow').hidden=!workflow;$('review').replaceChildren();if(workflow){const completed=NWCore.steps.filter(k=>workflow.stages[k]),next=NWCore.steps.find(k=>!workflow.stages[k]);$('stageStatus').textContent=(workflow.sample?'操作確認用サンプル（AI生成ではありません） / ':'')+`${completed.length}/4 段階完了`+(next?' · 次は「'+NWCore.titles[next]+'」':' · 全工程ドラフトを出力できます');if(next){try{chunks=NWCore.prompts(workflow,project);}catch(e){message(e.message,true);}}else{const r=workflow.stages.review;$('review').append(el('p',r.summary));for(const issue of r.issues)$('review').append(el('div',`${issue.severity==='blocking'?'要解消':'要確認'} / ${issue.target}\n${issue.finding}\n対応：${issue.required_action}`,'review-item '+issue.severity));}}showChunk();}
  function render(){$('projectName').value=project.name;$('saveStatus').textContent=dirty?'変更あり・未保存':'保存ファイル読込済み';renderSources();renderRequirements();renderFlow();}
  function replace(p,w){project=NWCore.clone(p);workflow=w?NWCore.clone(w):null;dirty=true;revoke();$('response').value='';render();}
  $('projectName').addEventListener('change',()=>{const s=$('projectName').value.trim();if(!s){$('projectName').value=project.name;message('案件名を入力してください。',true);return;}project.name=s;changed();});
  $('sources').addEventListener('change',()=>run(async()=>{const selected=[...$('sources').files];$('sources').value='';if(selected.length+project.sources.length>20)throw Error('資料は20ファイルまでです。');const added=[],errors=[];for(const f of selected){try{if(f.size>8*1024*1024)throw Error('8MBを超えています。');if(f.name.length>150)throw Error('ファイル名は150文字以内にしてください。');message(f.name+'を読み込んでいます…');const body=await NWImport.extract(f.name,await f.arrayBuffer());added.push({id:'S-'+crypto.randomUUID(),name:f.name,body});}catch(e){errors.push(f.name+'：'+e.message);}}if(added.length){project.sources.push(...added);changed();renderSources();}message(`${added.length}件取り込みました。要件候補の抽出を行ってください。`+(errors.length?'\n読み込めなかったファイル：\n'+errors.join('\n'):''),!!errors.length);}));
  action('extract',()=>{if(project.requirements.length&&!confirm('現在の要件一覧を抽出し直して置き換えます。手編集とAI回答はリセットされます。続けますか？'))return;const rows=NWCore.extractRequirements(project.sources);project.requirements=rows;changed();renderRequirements();message(rows.length+'件の要件候補を抽出しました。一覧を確認してください。');});
  action('addRequirement',()=>{if(project.requirements.length>=400)throw Error('要件は400件までです。');let i=1;while(project.requirements.some(r=>r.id==='REQ-'+String(i).padStart(3,'0')))i++;project.requirements.push({id:'REQ-'+String(i).padStart(3,'0'),text:'ここに要件を入力してください。',status:'unresolved',source_id:'',source:'手入力',quote:''});changed();renderRequirements();});
  action('save',()=>{NWCore.project(project);const text=JSON.stringify({format:'network-design-browser',version:1,project,workflow},null,2);if(new Blob([text]).size>16*1024*1024)throw Error('案件保存ファイルが16MBを超えています。対象を分割してください。');download(text,'network-design-project.json','application/json');dirty=false;$('saveStatus').textContent='保存用ファイルを作成済み';message('案件JSONをダウンロードしました。ブラウザーのダウンロード先をご確認ください。');});
  $('load').addEventListener('change',()=>run(async()=>{const f=$('load').files[0];$('load').value='';if(!f)return;if(f.size>16*1024*1024)throw Error('案件ファイルは16MB以内にしてください。');const v=NWCore.restore(await f.text());if(dirty&&!confirm('現在の未保存の案件を置き換えますか？'))return;replace(v.project,v.workflow);dirty=false;$('saveStatus').textContent='保存ファイル読込済み';message('案件と設計の進捗を読み込みました。');}));
  action('reset',()=>{if(!confirm('新規案件を開始します。現在の案件は必要なら先に保存してください。続けますか？'))return;replace({name:'ネットワーク更改案件',revision:1,sources:[],requirements:[]},null);message('新規案件を開始しました。');});
  action('demo',()=>{if(dirty&&!confirm('操作確認用サンプルで現在の案件を置き換えますか？'))return;const v=NWDemo();NWCore.project(v.project);NWCore.validateStages(v.workflow.stages,v.project);replace(v.project,v.workflow);message('操作確認用サンプルを読み込みました。AI生成の結果ではありません。「成果物ZIPを作成」で出力を試せます。');});
  action('start',()=>{if(workflow&&Object.keys(workflow.stages).length&&!confirm('取り込み済みのAI回答をリセットして依頼を作り直しますか？'))return;const next=NWCore.start(project);NWCore.prompts(next,project);workflow=next;dirty=true;revoke();renderFlow();$('saveStatus').textContent='変更あり・未保存';message('共通設計の依頼文を作成しました。すべての部分を順にCopilotへ貼り付けてください。');});
  action('prev',()=>{if(chunk>0)chunk--;showChunk();});action('next',()=>{if(chunk<chunks.length-1)chunk++;showChunk();});
  action('copy',async()=>{try{await navigator.clipboard.writeText(chunks[chunk]);message(`依頼文 ${chunk+1}/${chunks.length} をコピーしました。Copilotに貼り付けてください。`);}catch{$('prompt').focus();$('prompt').select();message('依頼文を選択しました。Ctrl+Cでコピーしてください。');}});
  action('promptFile',()=>download(chunks.map((s,i)=>`===== 部分 ${i+1} =====\n${s}`).join('\n\n'),'copilot-request.txt','text/plain;charset=utf-8'));
  action('accept',()=>{const next=NWCore.accept(workflow,project,$('response').value);workflow=next;dirty=true;revoke();$('response').value='';renderFlow();$('saveStatus').textContent='変更あり・未保存';message('回答の形式・参照関係を検証し、取り込みました。次の段階へ進んでください。');});
  $('responseFile').addEventListener('change',()=>run(async()=>{const f=$('responseFile').files[0];$('responseFile').value='';if(!f)return;if(f.size>8*1024*1024)throw Error('回答ファイルは8MB以内にしてください。');const s=await f.text();if(s.length>2000000)throw Error('回答は200万字以内にしてください。');$('response').value=s;message('JSON回答を読み込みました。「回答を検証して取り込む」を押してください。');}));
  action('export',async()=>{revoke();const data=await NWExport.bundle(project,workflow,s=>message(s));url=URL.createObjectURL(new Blob([data],{type:'application/zip'}));$('download').href=url;$('download').download=workflow.sample?'sample-network-lifecycle-draft.zip':'network-lifecycle-draft.zip';$('download').hidden=false;message('成果物ZIPを作成しました。「成果物ZIPをダウンロード」を押して保存してください。');});
  window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
  render();$('saveStatus').textContent='新規案件';message('起動しました。ファイルを取り込むか、操作確認用サンプルをお試しください。');
})();
